import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Container from "@/components/shared/Container";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Tidas Gold Gallery",
  description: "Generated by Tidas Gold Gallery",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container>
          <Header />
        </Container>
        {children}
      </body>
    </html>
  );
}
